"""One-off (2026-07-18): tidy the History tab of Stocks_Buy_Strategy.xlsx.

User requests:
  - Base text size Arial 9 across the tab (was Arial 10) — same base the Google
    Sheet should show after import.
  - Columns were running into each other (long headers like "Dealing/PTM Fees (£)"
    and "Value if Sold Today" in narrow columns) — widen every column to fit its
    content so nothing overflows.
  - Replace the cryptic Account number in column B with the OWNER's name
    (SANX002282 -> Paul, etc.), using the codebase's own ACCOUNT_OWNER map.

Safe/idempotent: backs the workbook up first, only touches the History sheet,
only rewrites column-B cells whose value is a known account number, and preserves
each cell's bold/italic/colour when resizing the font. Re-running is a no-op for
the account column (names aren't in ACCOUNT_OWNER) and re-applies the same widths.
History is a hand-maintained trade log (not regenerated by the pipeline), so these
changes persist.
"""
import datetime
import os
import shutil
import sys

import openpyxl
from openpyxl.styles import Font
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from spending_summary import ACCOUNT_OWNER  # single source of the account->owner map

BASE_FONT = "Arial"
BASE_SIZE = 9
WIDTH_CAP = 50
WIDTH_FLOOR = 8


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.expanduser("~"), "Downloads", "Stocks_Buy_Strategy.xlsx")
    if not os.path.exists(path):
        print(f"Not found: {path}")
        sys.exit(1)

    bak = path + ".bak-history-format-" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    shutil.copyfile(path, bak)
    print("Backed up ->", os.path.basename(bak))

    wb = openpyxl.load_workbook(path)
    ws = wb["History"]

    # 1. Account number -> owner name (column B, data rows only — never the stats
    #    block below, whose column B holds SUMPRODUCT formulas and labels).
    replaced = 0
    for r in range(1, ws.max_row + 1):
        cell = ws.cell(r, 2)
        v = cell.value
        if isinstance(v, str) and v.strip() in ACCOUNT_OWNER:
            cell.value = ACCOUNT_OWNER[v.strip()]
            replaced += 1

    # 2. Base font Arial 9 everywhere, preserving bold/italic/colour/underline.
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            f = cell.font
            cell.font = Font(name=BASE_FONT, size=BASE_SIZE, bold=f.bold,
                             italic=f.italic, underline=f.underline,
                             strike=f.strike, color=f.color, vertAlign=f.vertAlign)

    # 3. Fit column widths to content (header + non-formula data; formulas skipped
    #    since their displayed result length is unknown — the header governs those).
    for c in range(1, ws.max_column + 1):
        L = get_column_letter(c)
        longest = 0
        for r in range(1, ws.max_row + 1):
            v = ws.cell(r, c).value
            if v is None:
                continue
            s = str(v)
            if s.startswith("="):
                continue
            longest = max(longest, *(len(line) for line in s.split("\n")))
        width = min(max(longest + 2, WIDTH_FLOOR), WIDTH_CAP)
        ws.column_dimensions[L].width = width

    wb.save(path)
    print(f"Saved. Replaced {replaced} account numbers with owner names; "
          f"set Arial {BASE_SIZE}; refitted {ws.max_column} column widths.")


if __name__ == "__main__":
    main()
