"""Make outbound HTTPS verify correctly on this machine.

TWO separate problems, both diagnosed 2026-07-20 while setting up the Sheets
sync, and the second is the one that actually bites:

1. The interpreter the pipeline uses (AppData\\Local\\Python, a standalone
   build) ships with NO trust store: `ssl.get_default_verify_paths()` returns
   `cafile=None` and its OpenSSL default of
   `C:\\Program Files\\Common Files\\SSL/cert.pem` does not exist on Windows.

2. **Norton intercepts HTTPS.** Its "Web/Mail Shield" re-signs every TLS
   certificate — connect to oauth2.googleapis.com and the certificate you are
   handed is issued by `CN=Norton Web/Mail Shield Root, OU=generated by Norton
   Antivirus for SSL/TLS scanning`. Norton installs that root into the WINDOWS
   certificate store, which is why Chrome and Node are unaffected. Python
   verifies against certifi, which has never heard of it — so **pointing at
   certifi does not help**; an explicit `verify=certifi.where()` fails exactly
   the same way.

Both dissolve if Python verifies against the Windows store, which `truststore`
does. `ensure_ca_bundle()` injects it and falls back to the certifi env vars
where truststore isn't available (a machine without the AV, or a non-Windows
box). Call it BEFORE the first HTTPS request in any script that talks to an
external service.

Never sets `verify=False`. That would trade a local trust-config problem for a
silent, permanent downgrade of certificate checking on a path that carries
financial credentials — and it would also hide a genuine MITM if one ever
appeared. If certificates fail, the answer is to fix the trust store.
"""
import os
import ssl

_VARS = ("SSL_CERT_FILE", "REQUESTS_CA_BUNDLE")


def system_store_is_usable():
    """True if Python already has a CA file it can actually read."""
    paths = ssl.get_default_verify_paths()
    for p in (paths.cafile, paths.openssl_cafile):
        if p and os.path.exists(p):
            return True
    return bool(paths.capath and os.path.isdir(paths.capath)
                and os.listdir(paths.capath))


def ensure_ca_bundle():
    """Make certificate verification work, and say how it was achieved.

    Preferred: `truststore`, which verifies against the OS store — the only
    thing that satisfies Norton's re-signed certificates, and self-healing if
    Norton ever regenerates its root. Falls back to the certifi env vars.

    Returns a short description of what was applied, or None if nothing was
    needed. Idempotent: safe to call from every entry point.
    """
    try:
        import truststore
        truststore.inject_into_ssl()
        return "truststore (OS certificate store)"
    except ImportError:
        pass

    if any(os.environ.get(v) for v in _VARS):
        return os.environ.get("SSL_CERT_FILE") or os.environ.get("REQUESTS_CA_BUNDLE")
    if system_store_is_usable():
        return None
    try:
        import certifi
    except ImportError:
        return None
    bundle = certifi.where()
    if not os.path.exists(bundle):
        return None
    for v in _VARS:
        os.environ[v] = bundle
    return bundle


if __name__ == "__main__":
    paths = ssl.get_default_verify_paths()
    print(f"cafile         : {paths.cafile}")
    print(f"openssl_cafile : {paths.openssl_cafile}")
    print(f"system usable  : {system_store_is_usable()}")
    print(f"applied        : {ensure_ca_bundle()}")
